name: Main

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-southeast-2
  AWS_ACCOUNT: ${{ vars.AWS_ACCOUNT }}

#    AWS_PROFILE:

jobs:

  aws:

    runs-on: ubuntu-latest

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Check environment
        run: |
          env

      - name: Configure AWS credentials
        if: ${{ !env.ACT }}
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT }}:role/GitHubAction-AssumeRoleWithAction
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Configure AWS credentials
        if: ${{ env.ACT }}
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          aws-region: ${{ env.AWS_REGION }}

      - name: Sts - GetCallerIdentity
        run: |
          aws --no-cli-pager sts get-caller-identity

      - name: Lambda - List Functions
        run: |
          aws --no-cli-pager lambda list-functions

  native:

    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm' # See 'Options' for all available distributions
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Example step
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version

  gradle:
    needs: aws

    strategy:
      matrix:
        os: [ ubuntu-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        if: ${{ !env.ACT }}
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT }}:role/GitHubAction-AssumeRoleWithAction
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Configure AWS credentials
        if: ${{ env.ACT }}
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          aws-region: ${{ env.AWS_REGION }}

      - name: Configure Docker access
        if: ${{ env.ACT }}
        run: |
          sudo chown runner:docker /var/run/docker.sock
          docker ps

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle - BuildNativeLambda
        run: ./gradlew --console=plain :app:buildNativeLambda

      - name: Execute Gradle - Test
        run: ./gradlew --console=plain :app:test

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "21"

      - name: Install CDK
        run: |
          npm install -g aws-cdk

      - name: Check CDK
        run: |
          cdk --version
          cd infra
          cdk diff
